language: ruby
rvm:
  - 2.4.5

before_script:
  - chmod +x ci-build.sh

script: ./ci-build.sh

branches:
  only:
  - gh-pages
  - /pages-(.*)/

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false

cache: bundler

notification:
  email: false
